name: 🛠️ Build

vars:
  - icon_file: res/rubisco.ico
  - group: The C++ Plus Project
  - copyright: Copyright (C) 2024 The C++ Plus Project

steps:
  - name: 📦 Make source distribution directory
    mkdir: ${{ project.name }}-${{ project.version }}
  - mkdir: dist

  - name: 📦 Copy files to source distribution directory
    copy: ${{ cwd }}
    to: ${{ project.name }}-${{ project.version }}
    excludes: [
      ".git*",
      ".venv",
      "build",
      "dist",
      "__pycache__",
      "*.log",
      "*.7z",
      "*.gz",
      "*.xz",
      "*.zip",
      "*.whl",
      "*.mo",
      "*.pot",
      "*.py[cod]",
      "*$py.class",
      ".ruff_cache",
      ".pytype",
      ".vscode",
      ".rubisco/extensions",
      "result.json",
      "${{ project.name }}-*"
    ]

  - name: 📦 Packing the source distribution
    compress: ${{ project.name }}-${{ project.version }}
    to: dist/${{ project.name }}-${{ project.version }}
    format: [zip, tar.xz]

  - name: 🛠️ Build wheel distribution
    run:
      [
        "python",
        "-m",
        "build",
        "--wheel",
        "--outdir=dist",
        "--verbose",
      ]

  - name: 🛠️ Build standalone binary distribution
    run:
      [
        "python",
        "-m",
        "nuitka",
        "--standalone",
        "--warn-unusual-code",
        "--jobs=${{ nproc }}",
        "--output-filename=${{ project.name }}",
        "--output-dir=build",
        "--show-progress",
        "--show-memory",
        "--show-modules",
        "--windows-icon-from-ico=${{ icon_file }}",
        "--macos-app-icon=${{ icon_file }}",
        "--linux-icon=${{ icon_file }}",
        "--company-name=${{ group }}",
        "--product-name=${{ project.name }}",
        "--file-version=${{ project.version }}.0",
        "--product-version=${{ project.version }}",
        "--file-description=${{ project.description }} main executable",
        "--copyright=${{ copyright }}",
        "${{ project.name }}",
      ]

  - name: 🛠️ Build onefile standalone binary distribution
    run:
      [
        "python",
        "-m",
        "nuitka",
        "--onefile",
        "--standalone",
        "--warn-unusual-code",
        "--jobs=${{ nproc }}",
        "--output-filename=${{ project.name }}",
        "--output-dir=build",
        "--show-progress",
        "--show-memory",
        "--show-modules",
        "--windows-icon-from-ico=${{ icon_file }}",
        "--macos-app-icon=${{ icon_file }}",
        "--linux-icon=${{ icon_file }}",
        "--company-name=${{ group }}",
        "--product-name=${{ project.name }}",
        "--file-version=${{ project.version }}.0",
        "--product-version=${{ project.version }}",
        "--file-description=${{ project.description }} main executable",
        "--copyright=${{ copyright }}",
        "${{ project.name }}",
      ]

  - name: 📦 Rename the distribution directory
    copy: build/${{ project.name }}.dist
    to: ${{ project.name }}-standalone-${{ host.machine }}-${{ project.version }}

  - name: 📦 Copy files to distribution directory
    copy: LICENSE
    to: ${{ project.name }}-standalone-${{ host.machine }}-${{ project.version }}/LICENSE

  - name: 📦 Packing the standalone distribution
    compress: ${{ project.name }}-standalone-${{ host.machine }}-${{ project.version }}
    to: dist/${{ project.name }}-standalone-${{ host.machine }}-${{ project.version }}
    format: [zip, tar.xz]

  - name: 📦 Packing the onefile standalone distribution
    compress: build/${{ project.name }}
    to: dist/${{ project.name }}-onefile-standalone-${{ host.machine }}-${{ project.version }}
    format: [zip, tar.xz]
