name: 🛠️ Build cppp-repoutils

on:
  release:
    types: [published]

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: ubuntu-latest, target: unknown-linux-unknown }
          - { sys: windows-latest, target: unknown-windows-unknown }
          - { sys: macos-latest,  target: unknown-apple-unknown }

    runs-on: ${{ matrix.sys }}

    name: 🛠️ Build binary distribution

    defaults:
      run:
        shell: pwsh

    steps:

    #--------------------------------------------collect--------------------------------------------
      - name: ⬇️ Checkout the repository.
        uses: actions/checkout@v4
      
      - name: 📁 Setup cppp-repoutils.
        id: setup
        uses: cppp-project/cppp-repoutils@main
        with:
          host: ${{ matrix.target }}

      - name: 🛠️ Build the package.
        run: |
          cppp-repoutils --var "host=${{ steps.setup.outputs.host }}" --var "version=${{ steps.setup.outputs.tag }}" build
          if ($IsLinux) {
            cppp-repoutils --var "host=${{ steps.setup.outputs.host }}" --var "version=${{ steps.setup.outputs.tag }}" distpkg --type dpkg
          }
          Move-Item -Path "dist" -Destination "${{ steps.setup.outputs.pkgname }}-${{ steps.setup.outputs.host }}"

      - name: 📦 Make packages
        run: |
          cppp-compress --type tar "${{ steps.setup.outputs.pkgname }}-${{ steps.setup.outputs.host }}" .
          cppp-compress --type zip "${{ steps.setup.outputs.pkgname }}-${{ steps.setup.outputs.host }}" distpkg
          cppp-compress --type 7z "${{ steps.setup.outputs.pkgname }}-${{ steps.setup.outputs.host }}" distpkg
          cppp-compress --type xz "${{ steps.setup.outputs.pkgname }}-${{ steps.setup.outputs.host }}.tar" distpkg
          cppp-compress --type gzip "${{ steps.setup.outputs.pkgname }}-${{ steps.setup.outputs.host }}.tar" distpkg

          Set-Location distpkg
          Get-ChildItem | ForEach-Object {
            md5sum $_.Name > ($_.Name + ".md5")
            if ($IsWindows) {
              dos2unix ($_.Name + ".md5")
            }
          }
          Set-Location ${{ steps.setup.outputs.srcdir }}

      - name: ⬆️ Create release and upload assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            tag_name: ${{ steps.setup.outputs.tag }}
            files: ./distpkg/*
